export var Accidentals = {
    NATURAL: 0,
    SHARP: 1,
    FLAT: 2
};

export var COF = {
        [Accidentals.SHARP]: ['F', 'C', 'G', 'D', 'A', 'E', 'B'],
        [Accidentals.FLAT]: ['B', 'E', 'A', 'D', 'G', 'C', 'F'],
        C: {
            order: Accidentals.SHARP,
            C: Accidentals.NATURAL,
            D: Accidentals.NATURAL,
            E: Accidentals.NATURAL,
            F: Accidentals.NATURAL,
            G: Accidentals.NATURAL, 
            A: Accidentals.NATURAL,
            B: Accidentals.NATURAL,
        },
        F: {
            order: Accidentals.FLAT,
            F: Accidentals.NATURAL,
            G: Accidentals.NATURAL,
            A: Accidentals.NATURAL,
            B: Accidentals.FLAT,
            C: Accidentals.NATURAL,
            D: Accidentals.NATURAL,
            E: Accidentals.NATURAL,
        },
        B_FLAT: {
            order: Accidentals.FLAT,
            B: Accidentals.FLAT,
            C: Accidentals.NATURAL,
            D: Accidentals.NATURAL,
            E: Accidentals.FLAT,
            F: Accidentals.NATURAL,
            G: Accidentals.NATURAL,
            A: Accidentals.NATURAL,
        },
        E_FLAT: { 
            order: Accidentals.FLAT,
            E: Accidentals.FLAT,
            F: Accidentals.NATURAL,
            G: Accidentals.NATURAL,
            A: Accidentals.FLAT,
            B: Accidentals.FLAT,
            C: Accidentals.NATURAL,
            D: Accidentals.NATURAL,
        },
        A_FLAT: { 
            order: Accidentals.FLAT,
            A: Accidentals.FLAT,
            B: Accidentals.FLAT,
            C: Accidentals.NATURAL,
            D: Accidentals.FLAT,
            E: Accidentals.FLAT,
            F: Accidentals.NATURAL,
            G: Accidentals.NATURAL,
        },
        D_FLAT: { 
            order: Accidentals.FLAT,
            D: Accidentals.FLAT,
            E: Accidentals.FLAT,
            F: Accidentals.NATURAL,
            G: Accidentals.FLAT,
            A: Accidentals.FLAT,
            B: Accidentals.FLAT,
            C: Accidentals.NATURAL,
        },
        G_FLAT: { 
            order: Accidentals.FLAT,
            G: Accidentals.FLAT,
            A: Accidentals.FLAT,
            B: Accidentals.FLAT,
            C: Accidentals.FLAT,
            D: Accidentals.FLAT,
            E: Accidentals.FLAT,
            F: Accidentals.NATURAL,
        },
        F_SHARP: { 
            order: Accidentals.SHARP,
            F: Accidentals.SHARP,
            G: Accidentals.SHARP,
            A: Accidentals.SHARP,
            B: Accidentals.NATURAL,
            C: Accidentals.SHARP,
            D: Accidentals.SHARP,
            E: Accidentals.SHARP,
        },
        B: { 
            order: Accidentals.SHARP,
            B: Accidentals.NATURAL,
            C: Accidentals.SHARP,
            D: Accidentals.SHARP,
            E: Accidentals.NATURAL,
            F: Accidentals.SHARP,
            G: Accidentals.SHARP,
            A: Accidentals.SHARP,
        },
        E: { 
            order: Accidentals.SHARP,
            E: Accidentals.NATURAL,
            F: Accidentals.SHARP,
            G: Accidentals.SHARP,
            A: Accidentals.NATURAL,
            B: Accidentals.NATURAL,
            C: Accidentals.SHARP,
            D: Accidentals.SHARP,
        },
        A: { 
            order: Accidentals.SHARP,
            A: Accidentals.NATURAL,
            B: Accidentals.NATURAL,
            C: Accidentals.SHARP,
            D: Accidentals.NATURAL,
            E: Accidentals.NATURAL,
            F: Accidentals.SHARP,
            G: Accidentals.SHARP,
        },
        D: { 
            order: Accidentals.SHARP,
            D: Accidentals.NATURAL,
            E: Accidentals.NATURAL,
            F: Accidentals.SHARP,
            G: Accidentals.NATURAL,
            A: Accidentals.NATURAL,
            B: Accidentals.NATURAL,
            C: Accidentals.SHARP,
        },
        G: { 
            order: Accidentals.SHARP,
            G: Accidentals.NATURAL,
            A: Accidentals.NATURAL,
            B: Accidentals.NATURAL,
            C: Accidentals.NATURAL,
            D: Accidentals.NATURAL,
            E: Accidentals.NATURAL,
            F: Accidentals.SHARP
        },
    };

