import {Accidental, Note} from './music';
const SHARP = Accidental.SHARP,
    FLAT = Accidental.FLAT,
    NATURAL = Accidental.NATURAL;

var COF = {
    [SHARP]: [Note.F(), Note.C(), Note.G(), Note.D(),
        Note.A(4), Note.E(), Note.B(4)],
    [FLAT]: [Note.B(4), Note.E(), Note.A(4), Note.D(),
        Note.G(4), Note.C(), Note.F()],
    [Note.C().nameAndAccidental()]: {
        order: SHARP,
        notes: [Note.C(), Note.D(), Note.E(), Note.F(), Note.G(),
            Note.A(), Note.B(), Note.C(6)],
        C: NATURAL,
        D: NATURAL,
        E: NATURAL,
        F: NATURAL,
        G: NATURAL,
        A: NATURAL,
        B: NATURAL,
    },
    [Note.F().nameAndAccidental()]: {
        order: FLAT,
        notes: [Note.F(4), Note.G(4), Note.A(4), Note.B(4, FLAT), Note.C(),
            Note.D(), Note.E(), Note.F()],
        F: NATURAL,
        G: NATURAL,
        A: NATURAL,
        B: FLAT,
        C: NATURAL,
        D: NATURAL,
        E: NATURAL,
    },
    [Note.B(5, FLAT).nameAndAccidental()]: {
        order: FLAT,
        notes: [Note.B(4, FLAT), Note.C(), Note.D(), Note.E(5, FLAT),
            Note.F(), Note.G(), Note.A(), Note.B().flat()],
        B: FLAT,
        C: NATURAL,
        D: NATURAL,
        E: FLAT,
        F: NATURAL,
        G: NATURAL,
        A: NATURAL,
    },
    [Note.E(5, FLAT).nameAndAccidental()]: {
        order: FLAT,
        notes: [Note.E(4, FLAT), Note.F(4), Note.G(4), Note.A(4, FLAT),
            Note.B(4, FLAT), Note.C(), Note.D(), Note.E(5, FLAT)],
        E: FLAT,
        F: NATURAL,
        G: NATURAL,
        A: FLAT,
        B: FLAT,
        C: NATURAL,
        D: NATURAL,
    },
    [Note.A(5, FLAT).nameAndAccidental()]: {
        order: FLAT,
        notes: [Note.A(4, FLAT), Note.B(4, FLAT), Note.C(), Note.D(5, FLAT),
            Note.E(5, FLAT), Note.F(), Note.G(), Note.A(5, FLAT)],
        A: FLAT,
        B: FLAT,
        C: NATURAL,
        D: FLAT,
        E: FLAT,
        F: NATURAL,
        G: NATURAL,
    },
    [Note.D(5, FLAT).nameAndAccidental()]: {
        order: FLAT,
        notes: [Note.D(4, FLAT), Note.E(4, FLAT), Note.F(4, FLAT), Note.G(4, FLAT),
            Note.A(4, FLAT), Note.B(4, FLAT), Note.C(), Note.D(5, FLAT)],
        D: FLAT,
        E: FLAT,
        F: NATURAL,
        G: FLAT,
        A: FLAT,
        B: FLAT,
        C: NATURAL,
    },
    [Note.G(5, FLAT).nameAndAccidental()]: {
        order: FLAT,
        notes: [Note.G(4, FLAT), Note.A(4, FLAT), Note.B(4, FLAT),
            Note.C(5, FLAT), Note.D(5, FLAT), Note.E(5, FLAT),
            Note.F(), Note.G(5, FLAT)],
        G: FLAT,
        A: FLAT,
        B: FLAT,
        C: FLAT,
        D: FLAT,
        E: FLAT,
        F: NATURAL,
    },
    [Note.F(5, SHARP).nameAndAccidental()]: {
        order: SHARP,
        notes: [Note.F(4, SHARP), Note.G(4, SHARP), Note.A(4, SHARP), Note.B(4, NATURAL),
            Note.C(5, SHARP), Note.D(5, SHARP), Note.E(5, SHARP), Note.F(5, SHARP)],
        F: SHARP,
        G: SHARP,
        A: SHARP,
        B: NATURAL,
        C: SHARP,
        D: SHARP,
        E: SHARP,
    },
    [Note.B().nameAndAccidental()]: {
        order: SHARP,
        notes: [Note.B(4), Note.C(5, SHARP), Note.D(5, SHARP), Note.E(),
            Note.F(5, SHARP), Note.G(5, SHARP), Note.A(5, SHARP), Note.B()],
        B: NATURAL,
        C: SHARP,
        D: SHARP,
        E: NATURAL,
        F: SHARP,
        G: SHARP,
        A: SHARP,
    },
    [Note.E().nameAndAccidental()]: {
        order: SHARP,
        notes: [Note.E(4), Note.F(4, SHARP), Note.G(4, SHARP),
            Note.A(4), Note.B(4), Note.C(5, SHARP), Note.D(5, SHARP), Note.E()],
        E: NATURAL,
        F: SHARP,
        G: SHARP,
        A: NATURAL,
        B: NATURAL,
        C: SHARP,
        D: SHARP,
    },
    [Note.A().nameAndAccidental()]: {
        order: SHARP,
        notes: [Note.A(4), Note.B(4), Note.C(5, SHARP), Note.D(),
            Note.E(), Note.F(5, SHARP), Note.G(5, SHARP), Note.A()],
        A: NATURAL,
        B: NATURAL,
        C: SHARP,
        D: NATURAL,
        E: NATURAL,
        F: SHARP,
        G: SHARP,
    },
    [Note.D().nameAndAccidental()]: {
        order: SHARP,
        notes: [Note.D(4), Note.E(4), Note.F(4, SHARP), Note.G(4),
            Note.A(4), Note.B(4), Note.C(5, SHARP), Note.D()],
        D: NATURAL,
        E: NATURAL,
        F: SHARP,
        G: NATURAL,
        A: NATURAL,
        B: NATURAL,
        C: SHARP,
    },
    [Note.G().nameAndAccidental()]: {
        order: SHARP,
        notes: [Note.G(4), Note.A(4), Note.B(4), Note.C(), Note.D(),
            Note.E(), Note.F(5, SHARP), Note.G()],
        G: NATURAL,
        A: NATURAL,
        B: NATURAL,
        C: NATURAL,
        D: NATURAL,
        E: NATURAL,
        F: SHARP
    },
};

export = COF;