import {Accidental, Note} from 'music'; ///ts:import:generated

var COF = {
    [Accidental.SHARP]: [Note.F(), Note.C(), Note.G(), Note.D(),
        Note.A(4), Note.E(), Note.B(4)],
    [Accidental.FLAT]: [Note.B(4), Note.E(), Note.A(4), Note.D(),
        Note.G(4), Note.C(), Note.F()],
    [Note.C().nameAndAccidental()]: {
        order: Accidental.SHARP,
        C: Accidental.NATURAL,
        D: Accidental.NATURAL,
        E: Accidental.NATURAL,
        F: Accidental.NATURAL,
        G: Accidental.NATURAL,
        A: Accidental.NATURAL,
        B: Accidental.NATURAL,
    },
    [Note.F().nameAndAccidental()]: {
        order: Accidental.FLAT,
        F: Accidental.NATURAL,
        G: Accidental.NATURAL,
        A: Accidental.NATURAL,
        B: Accidental.FLAT,
        C: Accidental.NATURAL,
        D: Accidental.NATURAL,
        E: Accidental.NATURAL,
    },
    [Note.B().flat().nameAndAccidental()]: {
        order: Accidental.FLAT,
        B: Accidental.FLAT,
        C: Accidental.NATURAL,
        D: Accidental.NATURAL,
        E: Accidental.FLAT,
        F: Accidental.NATURAL,
        G: Accidental.NATURAL,
        A: Accidental.NATURAL,
    },
    [Note.E().flat().nameAndAccidental()]: {
        order: Accidental.FLAT,
        E: Accidental.FLAT,
        F: Accidental.NATURAL,
        G: Accidental.NATURAL,
        A: Accidental.FLAT,
        B: Accidental.FLAT,
        C: Accidental.NATURAL,
        D: Accidental.NATURAL,
    },
    [Note.A().flat().nameAndAccidental()]: {
        order: Accidental.FLAT,
        A: Accidental.FLAT,
        B: Accidental.FLAT,
        C: Accidental.NATURAL,
        D: Accidental.FLAT,
        E: Accidental.FLAT,
        F: Accidental.NATURAL,
        G: Accidental.NATURAL,
    },
    [Note.D().flat().nameAndAccidental()]: {
        order: Accidental.FLAT,
        D: Accidental.FLAT,
        E: Accidental.FLAT,
        F: Accidental.NATURAL,
        G: Accidental.FLAT,
        A: Accidental.FLAT,
        B: Accidental.FLAT,
        C: Accidental.NATURAL,
    },
    [Note.G().flat().nameAndAccidental()]: {
        order: Accidental.FLAT,
        G: Accidental.FLAT,
        A: Accidental.FLAT,
        B: Accidental.FLAT,
        C: Accidental.FLAT,
        D: Accidental.FLAT,
        E: Accidental.FLAT,
        F: Accidental.NATURAL,
    },
    [Note.F().sharp().nameAndAccidental()]: {
        order: Accidental.SHARP,
        F: Accidental.SHARP,
        G: Accidental.SHARP,
        A: Accidental.SHARP,
        B: Accidental.NATURAL,
        C: Accidental.SHARP,
        D: Accidental.SHARP,
        E: Accidental.SHARP,
    },
    [Note.B().nameAndAccidental()]: {
        order: Accidental.SHARP,
        B: Accidental.NATURAL,
        C: Accidental.SHARP,
        D: Accidental.SHARP,
        E: Accidental.NATURAL,
        F: Accidental.SHARP,
        G: Accidental.SHARP,
        A: Accidental.SHARP,
    },
    [Note.E().nameAndAccidental()]: {
        order: Accidental.SHARP,
        E: Accidental.NATURAL,
        F: Accidental.SHARP,
        G: Accidental.SHARP,
        A: Accidental.NATURAL,
        B: Accidental.NATURAL,
        C: Accidental.SHARP,
        D: Accidental.SHARP,
    },
    [Note.A().nameAndAccidental()]: {
        order: Accidental.SHARP,
        A: Accidental.NATURAL,
        B: Accidental.NATURAL,
        C: Accidental.SHARP,
        D: Accidental.NATURAL,
        E: Accidental.NATURAL,
        F: Accidental.SHARP,
        G: Accidental.SHARP,
    },
    [Note.D().nameAndAccidental()]: {
        order: Accidental.SHARP,
        D: Accidental.NATURAL,
        E: Accidental.NATURAL,
        F: Accidental.SHARP,
        G: Accidental.NATURAL,
        A: Accidental.NATURAL,
        B: Accidental.NATURAL,
        C: Accidental.SHARP,
    },
    [Note.G().nameAndAccidental()]: {
        order: Accidental.SHARP,
        G: Accidental.NATURAL,
        A: Accidental.NATURAL,
        B: Accidental.NATURAL,
        C: Accidental.NATURAL,
        D: Accidental.NATURAL,
        E: Accidental.NATURAL,
        F: Accidental.SHARP
    },
};

export = COF;